services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    PhpSolution\SwaggerUIGen\Bundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,ModelHandler/Operation/FormTypeBuilder}'

    Symfony\Component\Validator\Mapping\Factory\MetadataFactoryInterface: '@validator.mapping.class_metadata_factory'

    PhpSolution\SwaggerUIGen\Bundle\Service\DataProviderFactory: ~

    PhpSolution\SwaggerUIGen\Component\DataProvider\DataProviderInterface:
        class: 'PhpSolution\SwaggerUIGen\Component\DataProvider\YamlDataProvider'
        arguments: [[], [], []]
        factory: ['@PhpSolution\SwaggerUIGen\Bundle\Service\DataProviderFactory', 'createDataProvider']

    PhpSolution\SwaggerUIGen\Component\SwaggerProvider:
        class: 'PhpSolution\SwaggerUIGen\Component\SwaggerProvider'

    PhpSolution\SwaggerUIGen\Component\ModelHandler\GeneralFactory:
        class: 'PhpSolution\SwaggerUIGen\Component\ModelHandler\GeneralFactory'

    # Symfony Handlers
    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Swagger\DefinitionsBuilder:
        tags:
            - {name: 'swagger_uigen.swagger_data_normalizer'}
            - {name: 'swagger_uigen.model_builder.swagger'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Swagger\RoutePaths:
        tags:
            - {name: 'swagger_uigen.swagger_data_normalizer'}
            - {name: 'swagger_uigen.model_builder.swagger'}

    # Response Operation handlers
    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Operation\GeneralBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.operation'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Operation\AnnotationBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.operation'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Operation\FormTypeBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.operation'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Schema\SerializerBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.schema'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Schema\DoctrineBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.schema'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Schema\ValidatorBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.schema'}

    PhpSolution\SwaggerUIGen\Bundle\ModelHandler\Schema\PhpDoc\PhpDocSchemaBuilder:
        tags:
            - {name: 'swagger_uigen.model_builder.schema'}
